"""
Report Generator
================
Combines ML risk scores, SHAP explanations, and graph trust scores
into a rich Markdown report suitable for posting as a GitHub PR comment.
"""
from datetime import datetime
from typing import List, Dict, Any
from backend.db.models import PackageRisk
from backend.utils.logger import get_logger

logger = get_logger(__name__)

RISK_EMOJI = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}
RISK_BADGE = {
    "HIGH": "![HIGH](https://img.shields.io/badge/risk-HIGH-red)",
    "MEDIUM": "![MEDIUM](https://img.shields.io/badge/risk-MEDIUM-yellow)",
    "LOW": "![LOW](https://img.shields.io/badge/risk-LOW-brightgreen)",
}


def generate_pr_report(
    repo_full_name: str,
    pr_number: int,
    package_risks: List[PackageRisk],
    cluster_risks: List[Dict[str, Any]],
) -> str:
    """Generate Markdown body for the GitHub PR comment."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    high = [p for p in package_risks if p.risk_level == "HIGH"]
    medium = [p for p in package_risks if p.risk_level == "MEDIUM"]
    low = [p for p in package_risks if p.risk_level == "LOW"]

    lines = [
        "## 🔐 SupplyGuard — AI Supply Chain Risk Report",
        "",
        f"> **Repository:** `{repo_full_name}` &nbsp;|&nbsp; **PR:** #{pr_number} &nbsp;|&nbsp; **Scanned:** {now}",
        "",
        "---",
        "",
        "### 📊 Summary",
        "",
        f"| Packages Scanned | 🔴 HIGH | 🟡 MEDIUM | 🟢 LOW |",
        f"|:-:|:-:|:-:|:-:|",
        f"| {len(package_risks)} | {len(high)} | {len(medium)} | {len(low)} |",
        "",
    ]

    if high:
        lines += [
            "---",
            "### 🔴 High Risk Packages",
            "",
        ]
        for pkg in high:
            lines += _package_block(pkg)

    if medium:
        lines += [
            "---",
            "### 🟡 Medium Risk Packages",
            "",
        ]
        for pkg in medium:
            lines += _package_block(pkg)

    if low:
        lines += [
            "---",
            "<details>",
            "<summary>🟢 Low Risk Packages (click to expand)</summary>",
            "",
        ]
        for pkg in low:
            lines += _package_block(pkg)
        lines.append("</details>")

    # Cluster risk section
    risky_clusters = [c for c in cluster_risks if c["avg_risk"] > 0.5 and c["size"] > 1]
    if risky_clusters:
        lines += [
            "",
            "---",
            "### 🕸️ Ecosystem Risk Clusters",
            "",
            "The following dependency clusters show elevated ecosystem-level risk:",
            "",
        ]
        for cluster in risky_clusters[:3]:
            pkgs = ", ".join(f"`{p}`" for p in cluster["packages"])
            lines.append(
                f"- **Cluster** ({cluster['size']} packages): {pkgs}  "
                f"— Avg Risk: **{cluster['avg_risk']*100:.0f}%**"
            )

    lines += [
        "",
        "---",
        "",
        "<details>",
        "<summary>ℹ️ About SupplyGuard</summary>",
        "",
        "SupplyGuard uses **ML-based behavioural analysis** and **graph trust scoring** "
        "to detect risky npm dependencies *before* vulnerabilities are publicly disclosed. "
        "Predictions are based on 14 features including release patterns, maintainer history, "
        "CVE data, and ecosystem graph centrality.",
        "",
        "[View Full Dashboard →](http://localhost:5173)",
        "</details>",
        "",
        "---",
        f"*🤖 Generated by [SupplyGuard](https://github.com/supplyguard) · {now}*",
    ]

    return "\n".join(lines)


def _package_block(pkg: PackageRisk) -> List[str]:
    emoji = RISK_EMOJI.get(pkg.risk_level, "⚪")
    prob_pct = f"{pkg.risk_probability * 100:.1f}%"
    trust_pct = f"{pkg.trust_score * 100:.1f}%"

    block = [
        f"#### {emoji} `{pkg.package_name}` @ `{pkg.version}`",
        "",
        f"| Risk Score | Risk Level | Trust Score |",
        f"|:-:|:-:|:-:|",
        f"| **{prob_pct}** | **{pkg.risk_level}** | {trust_pct} |",
        "",
    ]

    if pkg.top_risk_factors:
        block.append("**⚠️ Risk Factors:**")
        for factor in pkg.top_risk_factors[:4]:
            block.append(f"- {factor}")
        block.append("")

    return block
